title: Computer Graphics and Multimedia Conference Deadlines # (Maintained by @JianweiHu94)

description: Countdowns to top Computer Graphics and Multimedia conference deadlines
author: JianweiHu94

domain: "www.cgmdeadlin.es"
baseurl: ""

github_username: JianweiHu94
github_repo: cgm-deadlines

markdown: kramdown
ga_id: UA-36274081-2

include: ['_pages']
