title: CAD Conference Deadlines # (Maintained by @JianweiHu94)

description: Countdowns to top *** conference deadlines
author: Jianwei Hu

domain: "caddeadlin.es"
baseurl: ""

github_username: JianweiHu94
github_repo: ca-deadlines

markdown: kramdown
ga_id: UA-36274081-2

include: ['_pages']
