title: Computer Graphics and Multimedia Conference Deadlines # (Maintained by @JianweiHu94)

description: Countdowns to top CG/CAD/MM conference deadlines
author: Jianwei Hu

domain: "cgmdeadlin.xyz"
baseurl: ""

github_username: JianweiHu94
github_repo: cad-deadlines

markdown: kramdown
ga_id: UA-36274081-2

include: ['_pages']
